[tool.poetry]
name = "pythonproject"
version = "0.1.0"
description = ""
authors = ["buyanthg <buyanthg@yndex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
