[tool.poetry]
name = "exam"
version = "0.1.0"
description = ""
authors = ["Zvyagina Mariya"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pygobject = "^3.46.0"
matplotlib = "^3.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
